# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vim-illuminate = {
    pname = "vim-illuminate";
    version = "e522e0dd742a83506db0a72e1ced68c9c130f185";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "vim-illuminate";
      rev = "e522e0dd742a83506db0a72e1ced68c9c130f185";
      fetchSubmodules = false;
      sha256 = "sha256-o0D1edrsHkaljrzBFZXjdxiK/5ziCGJxM/kYNJgBI1E=";
    };
    date = "2024-04-18";
  };
}
