# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vim-illuminate = {
    pname = "vim-illuminate";
    version = "305bf07b919ac526deb5193280379e2f8b599926";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "vim-illuminate";
      rev = "305bf07b919ac526deb5193280379e2f8b599926";
      fetchSubmodules = false;
      sha256 = "sha256-KNIu4cNyZddZSRS8KZ0U0T8uSSLJu8iqNLQN8e+Bv94=";
    };
    date = "2024-02-03";
  };
}
