# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vim-illuminate = {
    pname = "vim-illuminate";
    version = "3bd2ab64b5d63b29e05691e624927e5ebbf0fb86";
    src = fetchFromGitHub {
      owner = "RRethy";
      repo = "vim-illuminate";
      rev = "3bd2ab64b5d63b29e05691e624927e5ebbf0fb86";
      fetchSubmodules = false;
      sha256 = "sha256-KdF52Ho4c8VKt3qBgBIxYnDK8upXqlUj+YnL2IaJdHQ=";
    };
    date = "2023-10-06";
  };
}
