# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-jdtls = {
    pname = "nvim-jdtls";
    version = "894c044034e0d5f78a22602f1440bfe70aff58ee";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-jdtls";
      rev = "894c044034e0d5f78a22602f1440bfe70aff58ee";
      fetchSubmodules = false;
      sha256 = "sha256-HjdLKb8AZRJGAMREZdf3RMPLzOSgP6GYII9moSkCe40=";
    };
    date = "2024-02-09";
  };
}
