# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-jdtls = {
    pname = "nvim-jdtls";
    version = "44403b2ef6c6285cfd9a3b4fa9a0d746ddae4b45";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-jdtls";
      rev = "44403b2ef6c6285cfd9a3b4fa9a0d746ddae4b45";
      fetchSubmodules = false;
      sha256 = "sha256-mwUZJW3x1MB78ocUPfIetOUaPr8qCNQba6fn5Fln0TQ=";
    };
    date = "2023-11-21";
  };
}
