# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-jdtls = {
    pname = "nvim-jdtls";
    version = "503a399e0d0b5d432068ab5ae24b9848891b0d53";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-jdtls";
      rev = "503a399e0d0b5d432068ab5ae24b9848891b0d53";
      fetchSubmodules = false;
      sha256 = "sha256-jkMeEVdxrKWuwoDIBuKYzGpYL2UFhlOnSJunKUbWCGM=";
    };
    date = "2023-11-01";
  };
}
