# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  one-small-step-for-vimkind = {
    pname = "one-small-step-for-vimkind";
    version = "cd2500ab74addeed6ac260a008dd649c01d3ba12";
    src = fetchFromGitHub {
      owner = "jbyuki";
      repo = "one-small-step-for-vimkind";
      rev = "cd2500ab74addeed6ac260a008dd649c01d3ba12";
      fetchSubmodules = false;
      sha256 = "sha256-f1vxmjSnsSAylKOV4+5z3Iy71ENO2q4D8cyfrWV0GMA=";
    };
    date = "2024-03-17";
  };
}
