# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  one-small-step-for-vimkind = {
    pname = "one-small-step-for-vimkind";
    version = "edbb34ee779049f2071dc7becff0bbf51c865906";
    src = fetchFromGitHub {
      owner = "jbyuki";
      repo = "one-small-step-for-vimkind";
      rev = "edbb34ee779049f2071dc7becff0bbf51c865906";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-aKDXes5GQiLbnGaCU1xHG4emK+5TzLcpNqwxIz1gKWs=";
    };
    date = "2023-09-09";
  };
}
