# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  one-small-step-for-vimkind = {
    pname = "one-small-step-for-vimkind";
    version = "aaee281bdaa3141d9d0cdb3dec468532da61124f";
    src = fetchFromGitHub {
      owner = "jbyuki";
      repo = "one-small-step-for-vimkind";
      rev = "aaee281bdaa3141d9d0cdb3dec468532da61124f";
      fetchSubmodules = false;
      sha256 = "sha256-VACSEN50FSzQmAjpFW45yXvc68wnRhzfboYvps3sOBE=";
    };
    date = "2023-12-23";
  };
}
