# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  diffview-nvim = {
    pname = "diffview-nvim";
    version = "d38c1b5266850f77f75e006bcc26213684e1e141";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "d38c1b5266850f77f75e006bcc26213684e1e141";
      fetchSubmodules = false;
      sha256 = "sha256-ZlEF5VZaE2LIfynaAzbcN9LP++0eAvyGzMF70Qds2K8=";
    };
    date = "2023-10-11";
  };
}
