# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  diffview-nvim = {
    pname = "diffview-nvim";
    version = "a111d19ccceac6530448d329c63f998f77b5626e";
    src = fetchFromGitHub {
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "a111d19ccceac6530448d329c63f998f77b5626e";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-4PqgjD7qNWFJmMxOqxu6AEXF3A4jcZBx0uHoRSUi2dc=";
    };
    date = "2023-09-17";
  };
}
