# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "4.13.0";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "4.13.0";
      fetchSubmodules = false;
      sha256 = "sha256-kd0IgnjkLWGgNE1WoY4w6WpTpZBkE/YH6Y1mbupHJFs=";
    };
  };
}
