# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "4.8.0";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "4.8.0";
      fetchSubmodules = false;
      sha256 = "sha256-TMJIo4wu5JZ9BrctYkDDZKdqx/l7gYRZAnEatMRH9d0=";
    };
  };
}
