# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  rustaceanvim = {
    pname = "rustaceanvim";
    version = "4.21.0";
    src = fetchFromGitHub {
      owner = "mrcjkb";
      repo = "rustaceanvim";
      rev = "4.21.0";
      fetchSubmodules = false;
      sha256 = "sha256-H8mGJ9kEJgst/EhN7H+R/6jnzVnz+OvVTCv22WrYaNY=";
    };
  };
}
