# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "9ce85b0f7dcfe5358c0be937ad23e456907d410b";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "9ce85b0f7dcfe5358c0be937ad23e456907d410b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-5+KVKUHMPhJzY9YuBOxB5qB3aCx+tKm9+JRw4cwvAuM=";
    };
    date = "2023-09-12";
  };
}
