# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "4f71c0c4a196ceb656c824a70792f3df3ce6bb6d";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "4f71c0c4a196ceb656c824a70792f3df3ce6bb6d";
      fetchSubmodules = false;
      sha256 = "sha256-AWJHxehKUkEV6N+n78urqHjMVUsMfDK3lvHs/VxhKE8=";
    };
    date = "2024-01-29";
  };
}
