# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  plenary-nvim = {
    pname = "plenary-nvim";
    version = "663246936325062427597964d81d30eaa42ab1e4";
    src = fetchFromGitHub {
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "663246936325062427597964d81d30eaa42ab1e4";
      fetchSubmodules = false;
      sha256 = "sha256-awRAI1ov9OBt6VuNxk/qjPTSPBYsMJzURKVV+IA7kok=";
    };
    date = "2024-01-21";
  };
}
