# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lualine-nvim = {
    pname = "lualine-nvim";
    version = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "45e27ca739c7be6c49e5496d14fcf45a303c3a63";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-oJ3jXb9qvViaIpiyKkTaXuye2BxiOp7kKtNw9igERVg=";
    };
    date = "2023-08-03";
  };
}
