# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lualine-nvim = {
    pname = "lualine-nvim";
    version = "566b7036f717f3d676362742630518a47f132fff";
    src = fetchFromGitHub {
      owner = "nvim-lualine";
      repo = "lualine.nvim";
      rev = "566b7036f717f3d676362742630518a47f132fff";
      fetchSubmodules = false;
      sha256 = "sha256-do28EEtiu14NAroVblx8FJLCk8CVNmpm8RaTbcDHtvk=";
    };
    date = "2023-12-26";
  };
}
