# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  flash-nvim = {
    pname = "flash-nvim";
    version = "v1.18.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "flash.nvim";
      rev = "v1.18.0";
      fetchSubmodules = false;
      sha256 = "sha256-5MRiIS2wXZuDCcRdhbH5hPbJ9j5BIHDYdE1IlE6uf5Q=";
    };
  };
}
