# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  flash-nvim = {
    pname = "flash-nvim";
    version = "v1.18.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "flash.nvim";
      rev = "v1.18.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-/WvWX8njr+ad464ifs7LPqTIuqtbM4Zjr/RP0U0k+Zw=";
    };
  };
}
