# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  flash-nvim = {
    pname = "flash-nvim";
    version = "v1.17.3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "flash.nvim";
      rev = "v1.17.3";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-DxmDf7jwE5yvmbRG5Y6hkK+iRRHJIaCJ0IAM+vfwoHc=";
    };
  };
}
