# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  harpoon = {
    pname = "harpoon";
    version = "ccae1b9bec717ae284906b0bf83d720e59d12b91";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "ccae1b9bec717ae284906b0bf83d720e59d12b91";
      fetchSubmodules = false;
      sha256 = "sha256-SIqssvuNnkw1YbEEElLYCHmh9OLnoHzggXNIZMb3jYI=";
    };
    date = "2023-12-26";
  };
}
