# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  basedpyright = {
    pname = "basedpyright";
    version = "v1.11.0";
    src = fetchFromGitHub {
      owner = "DetachHead";
      repo = "basedpyright";
      rev = "v1.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-zkL3HNbaL4elSOq2cmfycD/D2VKTbMMZvmdK2mHbPSM=";
    };
  };
}
