# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  basedpyright = {
    pname = "basedpyright";
    version = "v1.10.1";
    src = fetchFromGitHub {
      owner = "DetachHead";
      repo = "basedpyright";
      rev = "v1.10.1";
      fetchSubmodules = false;
      sha256 = "sha256-BAFn66mM5NRoPdH/XLuj1tWUYehj9Zg93/JWQdw0iB4=";
    };
  };
}
