# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neodev-nvim = {
    pname = "neodev-nvim";
    version = "3408a4daeca5ff8f41cb2c668b6d8fcc665f793a";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neodev.nvim";
      rev = "3408a4daeca5ff8f41cb2c668b6d8fcc665f793a";
      fetchSubmodules = false;
      sha256 = "sha256-BnrIvG4sHgDGmbJLGQk637Zm5IMzZ6kMKsx7TqXgL6M=";
    };
    date = "2024-01-25";
  };
}
