# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neodev-nvim = {
    pname = "neodev-nvim";
    version = "365ef03dbf5b8579e6eb205b3500fc3bee17484a";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "neodev.nvim";
      rev = "365ef03dbf5b8579e6eb205b3500fc3bee17484a";
      fetchSubmodules = false;
      sha256 = "sha256-NeEGvWYFssSoHikYEZsDjm9NO1+3WRKDXvCG6oniJqw=";
    };
    date = "2024-02-14";
  };
}
