# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  crates-nvim = {
    pname = "crates-nvim";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "Saecki";
      repo = "crates.nvim";
      rev = "v0.3.0";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-cvdZK+LlRs4GAy/0gOy49sV9Dp/5H3DhMZ8m76/f1Zo=";
    };
  };
}
