# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  crates-nvim = {
    pname = "crates-nvim";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "Saecki";
      repo = "crates.nvim";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-728ua02jB2aZw5Ge6f8iJH4AYqBpKpeR/e6sDvu7RAE=";
    };
  };
}
