# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  inc-rename-nvim = {
    pname = "inc-rename-nvim";
    version = "5e03e986625961d1fac296d1bf332a6510c3add6";
    src = fetchFromGitHub {
      owner = "smjonas";
      repo = "inc-rename.nvim";
      rev = "5e03e986625961d1fac296d1bf332a6510c3add6";
      fetchSubmodules = false;
      sha256 = "sha256-+Vxm0/HBdzCZi32ymro7SMZPfJ7EJE587cZsfD2IkX0=";
    };
    date = "2024-04-02";
  };
}
