# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  inc-rename-nvim = {
    pname = "inc-rename-nvim";
    version = "6f9b5f9cb237e12935144cdc535322b8c93c1b25";
    src = fetchFromGitHub {
      owner = "smjonas";
      repo = "inc-rename.nvim";
      rev = "6f9b5f9cb237e12935144cdc535322b8c93c1b25";
      fetchSubmodules = false;
      sha256 = "sha256-troS1bXmhhvJeetn0YD/vSqknhLjevA+q85fX7FWJC8=";
    };
    date = "2023-12-28";
  };
}
