# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  plugin-beancount-nvim = {
    pname = "plugin-beancount-nvim";
    version = "067e6a26a828437ecd72a250a656bf63d5a33d32";
    src = fetchFromGitHub ({
      owner = "polarmutex";
      repo = "beancount.nvim";
      rev = "067e6a26a828437ecd72a250a656bf63d5a33d32";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-J5+uZciE9lPfvcifnauIGi4A3wC/QQbPr7/4XpKhfE8=";
    });
    date = "2023-01-27";
  };
  plugin-cmp-buffer = {
    pname = "plugin-cmp-buffer";
    version = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-buffer";
      rev = "3022dbc9166796b644a841a02de8dd1cc1d311fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-mJgNij0eTnAM3vIbuECF9mZ/J42v6k441z/vUNJRGSc=";
    });
    date = "2022-08-10";
  };
  plugin-cmp-calc = {
    pname = "plugin-cmp-calc";
    version = "50792f34a628ea6eb31d2c90e8df174671e4e7a0";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-calc";
      rev = "50792f34a628ea6eb31d2c90e8df174671e4e7a0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-yOLDr3E63k1rwacDeWw35/8OPfUb2hBDgZ0Q4Wkjn7Y=";
    });
    date = "2022-11-16";
  };
  plugin-cmp-cmdline = {
    pname = "plugin-cmp-cmdline";
    version = "23c51b2a3c00f6abc4e922dbd7c3b9aca6992063";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-cmdline";
      rev = "23c51b2a3c00f6abc4e922dbd7c3b9aca6992063";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-WyYPNwex0w08oR7dJ0MX6hROL7W48OfzuM+EhA9mC58=";
    });
    date = "2022-11-27";
  };
  plugin-cmp-dap = {
    pname = "plugin-cmp-dap";
    version = "d16f14a210cd28988b97ca8339d504533b7e09a4";
    src = fetchFromGitHub ({
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "d16f14a210cd28988b97ca8339d504533b7e09a4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-tumnAAPImLQGKJ3yaQm1xVF1prZo1pZ81hsYlfkRtfc=";
    });
    date = "2022-11-13";
  };
  plugin-cmp-emoji = {
    pname = "plugin-cmp-emoji";
    version = "19075c36d5820253d32e2478b6aaf3734aeaafa0";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-emoji";
      rev = "19075c36d5820253d32e2478b6aaf3734aeaafa0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-YE9dV+WI08gzbcyA18dufwFoHP7BeWFyLTvj9VCKWPc=";
    });
    date = "2021-09-28";
  };
  plugin-cmp-nvim-lsp = {
    pname = "plugin-cmp-nvim-lsp";
    version = "59224771f91b86d1de12570b4070fe4ad7cd1eeb";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp";
      rev = "59224771f91b86d1de12570b4070fe4ad7cd1eeb";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-E87EKtMWUJT4RO9JzTh0ZrKbEoRtE1cTdGq4HD6bIFQ=";
    });
    date = "2022-11-16";
  };
  plugin-cmp-nvim-lsp-signature-help = {
    pname = "plugin-cmp-nvim-lsp-signature-help";
    version = "d2768cb1b83de649d57d967085fe73c5e01f8fd7";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-nvim-lsp-signature-help";
      rev = "d2768cb1b83de649d57d967085fe73c5e01f8fd7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-7jK6NzHAwW+ux4ZMWaaHdDz39Ws5+3bx0EpMjgpk+yA=";
    });
    date = "2022-10-14";
  };
  plugin-cmp-omni = {
    pname = "plugin-cmp-omni";
    version = "8457e4144ea2fc5efbadb7d22250d5ee8f8862ba";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-omni";
      rev = "8457e4144ea2fc5efbadb7d22250d5ee8f8862ba";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-rQvAWD49YerLPu7GW/UOZksvpkv0sBlX1sF8XnrM4l4=";
    });
    date = "2022-11-17";
  };
  plugin-cmp-path = {
    pname = "plugin-cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-Fm7L5IJ/Dp+lf9qsMHzFLF85oaaU5wXr/rEa5fzI6c8=";
    });
    date = "2022-10-03";
  };
  plugin-crates-nvim = {
    pname = "plugin-crates-nvim";
    version = "c2e9929c3ac40776c30bc7b328a7dff98756050a";
    src = fetchFromGitHub ({
      owner = "Saecki";
      repo = "crates.nvim";
      rev = "c2e9929c3ac40776c30bc7b328a7dff98756050a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-YumnrsUWRr1mwohAaLdHWNKQvziBLGawW7xc9GwRBxY=";
    });
    date = "2023-01-24";
  };
  plugin-diffview-nvim = {
    pname = "plugin-diffview-nvim";
    version = "dc77f487b292c4a89dd437d80331e3aacbe3aaed";
    src = fetchFromGitHub ({
      owner = "sindrets";
      repo = "diffview.nvim";
      rev = "dc77f487b292c4a89dd437d80331e3aacbe3aaed";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-Nmk5W3Z1OyvwiGY2Ex1f4Pz91o6uLx9/FwvAjHYgIMo=";
    });
    date = "2023-01-27";
  };
  plugin-gitsigns-nvim = {
    pname = "plugin-gitsigns-nvim";
    version = "0d4fe37ba5285171f3729da955955205f3fa945b";
    src = fetchFromGitHub ({
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "0d4fe37ba5285171f3729da955955205f3fa945b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-/v9/Cr9CnGK9NNAcCzL5JtaSr4z9S26cCBbSLzCCDM8=";
    });
    date = "2023-01-27";
  };
  plugin-gitworktree-nvim = {
    pname = "plugin-gitworktree-nvim";
    version = "d7f4e2584e81670154f07ca9fa5dd791d9c1b458";
    src = fetchFromGitHub ({
      owner = "ThePrimeagen";
      repo = "git-worktree.nvim";
      rev = "d7f4e2584e81670154f07ca9fa5dd791d9c1b458";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-LWL5hNqUNhzqeEWlpagTjNM7Tu17fybmtD4DrPdSrbI=";
    });
    date = "2021-12-24";
  };
  plugin-harpoon = {
    pname = "plugin-harpoon";
    version = "8c0bb0a328e57278f4783bb0e2ea32f296d36db1";
    src = fetchFromGitHub ({
      owner = "ThePrimeagen";
      repo = "harpoon";
      rev = "8c0bb0a328e57278f4783bb0e2ea32f296d36db1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-DsyMDITtDXdnr5wtHa99ek4yPA2aP6KclOyxBRdJjQ0=";
    });
    date = "2023-01-23";
  };
  plugin-heirline-nvim = {
    pname = "plugin-heirline-nvim";
    version = "b07ae7e499fecc263f38d1db7feeb2da227df370";
    src = fetchFromGitHub ({
      owner = "rebelot";
      repo = "heirline.nvim";
      rev = "b07ae7e499fecc263f38d1db7feeb2da227df370";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-0L7LzEDVgfSHaBbs+1a7prtqxuljYtUgFgCIDm1xB+s=";
    });
    date = "2023-01-11";
  };
  plugin-lazy-nvim = {
    pname = "plugin-lazy-nvim";
    version = "15fe46a728b7473d4cae368838bbc1c79c3a3f48";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "lazy.nvim";
      rev = "15fe46a728b7473d4cae368838bbc1c79c3a3f48";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-hj5vFNaxOCKTuLEOTYnSO/U9EBtOruvKN+X17h1GHWM=";
    });
    date = "2023-01-25";
  };
  plugin-lspformat-nvim = {
    pname = "plugin-lspformat-nvim";
    version = "ca0df5c8544e51517209ea7b86ecc522c98d4f0a";
    src = fetchFromGitHub ({
      owner = "lukas-reineke";
      repo = "lsp-format.nvim";
      rev = "ca0df5c8544e51517209ea7b86ecc522c98d4f0a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-9cY0QLyzkGv7KDVUXMXZj5TKZSSbXL6JN/Al3nhn5ps=";
    });
    date = "2022-11-25";
  };
  plugin-lspkind-nvim = {
    pname = "plugin-lspkind-nvim";
    version = "c68b3a003483cf382428a43035079f78474cd11e";
    src = fetchFromGitHub ({
      owner = "onsails";
      repo = "lspkind.nvim";
      rev = "c68b3a003483cf382428a43035079f78474cd11e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-LIbh63B+Sbu3/ahSPSa6K/X1Sqq32t9d9p/InaKu01I=";
    });
    date = "2022-09-22";
  };
  plugin-neodev-nvim = {
    pname = "plugin-neodev-nvim";
    version = "8b14787044352eb264cd105f5b0762565e1779f5";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "neodev.nvim";
      rev = "8b14787044352eb264cd105f5b0762565e1779f5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-ispS2x84q42Ytal3FlIu1Y32OWas1uBq4bCg+mi+JE0=";
    });
    date = "2023-01-26";
  };
  plugin-neogit = {
    pname = "plugin-neogit";
    version = "da8b0931724864e20c541ec1ec51f998cf8212f9";
    src = fetchFromGitHub ({
      owner = "TimUntersberger";
      repo = "neogit";
      rev = "da8b0931724864e20c541ec1ec51f998cf8212f9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-1d8HCLLkzCY76GR6F+0NkThqoAHW+qf9zdhKBLQaWgM=";
    });
    date = "2023-01-27";
  };
  plugin-noice-nvim = {
    pname = "plugin-noice-nvim";
    version = "20f47dcebd24c84650bb8ed57d8349cc53dffd3f";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "noice.nvim";
      rev = "20f47dcebd24c84650bb8ed57d8349cc53dffd3f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-ML0UBzNxylT7Zezt4E2QiiCoTcd3xy57k5T7HV7FlgA=";
    });
    date = "2023-01-25";
  };
  plugin-nui-nvim = {
    pname = "plugin-nui-nvim";
    version = "b99e6cb13dc51768abc1c4c8585045a0c0459ef1";
    src = fetchFromGitHub ({
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "b99e6cb13dc51768abc1c4c8585045a0c0459ef1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-h7RwCFCE7jCw4DYYYtDVmkY8PsiIwDdFbExj1++dhlA=";
    });
    date = "2023-01-16";
  };
  plugin-null-ls-nvim = {
    pname = "plugin-null-ls-nvim";
    version = "2ff0a4ed1985d04bae3f21915ee0b1be3932c164";
    src = fetchFromGitHub ({
      owner = "jose-elias-alvarez";
      repo = "null-ls.nvim";
      rev = "2ff0a4ed1985d04bae3f21915ee0b1be3932c164";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-saugVybYZs6eAWBQ7f9aPrOZeSnMVw6wXTjX6vIzYQE=";
    });
    date = "2023-01-26";
  };
  plugin-nvim-cmp = {
    pname = "plugin-nvim-cmp";
    version = "e7e2ef7031db8e0cfad7ad9916ec766ddd9dbb3b";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "nvim-cmp";
      rev = "e7e2ef7031db8e0cfad7ad9916ec766ddd9dbb3b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-ea2lWM/ZiqN0Xg0RlKFpcX2zXrBldLnpn0xS6mjfESA=";
    });
    date = "2023-01-26";
  };
  plugin-nvim-colorizer = {
    pname = "plugin-nvim-colorizer";
    version = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
    src = fetchFromGitHub ({
      owner = "norcalli";
      repo = "nvim-colorizer.lua";
      rev = "36c610a9717cc9ec426a07c8e6bf3b3abcb139d6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-AZveV57JRp+S330jWarDtNxW0seTefmhxfYysVxEsco=";
    });
    date = "2020-06-11";
  };
  plugin-nvim-dap = {
    pname = "plugin-nvim-dap";
    version = "43695d2cb7992436c5533cbfd58ed8d53d2c8be3";
    src = fetchFromGitHub ({
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "43695d2cb7992436c5533cbfd58ed8d53d2c8be3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-7gZ0evG7LcQ6HpONu2PwXiXoyVecuR5lZli1i8RaNf4=";
    });
    date = "2023-01-27";
  };
  plugin-nvim-dap-python = {
    pname = "plugin-nvim-dap-python";
    version = "d4400d075c21ed8fb8e8ac6a5ff56f58f6e93531";
    src = fetchFromGitHub ({
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "d4400d075c21ed8fb8e8ac6a5ff56f58f6e93531";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-0OY9/66Wz73BaWv5w+xSIk9If9GFlTo43IQdYhGi28A=";
    });
    date = "2022-12-18";
  };
  plugin-nvim-dap-ui = {
    pname = "plugin-nvim-dap-ui";
    version = "ed2c345fa8edd3f6049b9647a74a5d8cc5318ce3";
    src = fetchFromGitHub ({
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "ed2c345fa8edd3f6049b9647a74a5d8cc5318ce3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-2afOIg7zRe1TKvlFLjIfxnHmHbyAezUjh7wZ+sTvmTU=";
    });
    date = "2023-01-27";
  };
  plugin-nvim-dap-virtual-text = {
    pname = "plugin-nvim-dap-virtual-text";
    version = "191345947a92a5188d791e9786a5b4f205dcaca3";
    src = fetchFromGitHub ({
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "191345947a92a5188d791e9786a5b4f205dcaca3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-9hHRLJdbNdO1evALo1siz4aVNOv16lQ0pxAHSTIkJIY=";
    });
    date = "2023-01-16";
  };
  plugin-nvim-lspconfig = {
    pname = "plugin-nvim-lspconfig";
    version = "1e988250a0f52a68ddb72905d623405d634e9c5d";
    src = fetchFromGitHub ({
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "1e988250a0f52a68ddb72905d623405d634e9c5d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-8M7FsPjx0vKVcAEaI/UNf6fuhjfe1F5xuQwY3oayHNY=";
    });
    date = "2023-01-27";
  };
  plugin-nvim-treesitter = {
    pname = "plugin-nvim-treesitter";
    version = "a422d8508d73e9b1959edfbe94049e218d04e5f2";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "a422d8508d73e9b1959edfbe94049e218d04e5f2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-Nrfcnsh2833sCGU/nfXl7PWz/ZUWon1pfM30vGnKfHI=";
    });
    date = "2023-01-28";
  };
  plugin-nvim-treesitter-playground = {
    pname = "plugin-nvim-treesitter-playground";
    version = "c19bcfd6a3681bc876e1b861f6685bfc04972d0d";
    src = fetchFromGitHub ({
      owner = "nvim-treesitter";
      repo = "playground";
      rev = "c19bcfd6a3681bc876e1b861f6685bfc04972d0d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-0fZB9f51Udg/vkyJNUPIhlpgb0PMwyls3ISu2d4rRHk=";
    });
    date = "2023-01-24";
  };
  plugin-nvim-web-devicons = {
    pname = "plugin-nvim-web-devicons";
    version = "3548363849878ef895ce54edda02421279b419d8";
    src = fetchFromGitHub ({
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "3548363849878ef895ce54edda02421279b419d8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-ZpCaA7swV2zNWtamljJiL0gGHZSz8OLUa7+4XzHmosI=";
    });
    date = "2023-01-24";
  };
  plugin-one-small-step-for-vimkind = {
    pname = "plugin-one-small-step-for-vimkind";
    version = "233c8940488d4072f9f8058798984cb68a49a319";
    src = fetchFromGitHub ({
      owner = "jbyuki";
      repo = "one-small-step-for-vimkind";
      rev = "233c8940488d4072f9f8058798984cb68a49a319";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-xVptZkTzjGZu+hDAbgdmCIpAX1EvnIfbxVAv3vVQyF0=";
    });
    date = "2023-01-08";
  };
  plugin-plenary-nvim = {
    pname = "plugin-plenary-nvim";
    version = "1c7e3e6b0f4dd5a174fcea9fda8a4d7de593b826";
    src = fetchFromGitHub ({
      owner = "nvim-lua";
      repo = "plenary.nvim";
      rev = "1c7e3e6b0f4dd5a174fcea9fda8a4d7de593b826";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-RUZBUVqAjtPQ/etLh5KrXDJJf0VzRVx4TeENYq08NXw=";
    });
    date = "2023-01-10";
  };
  plugin-rust-tools-nvim = {
    pname = "plugin-rust-tools-nvim";
    version = "b297167d9e01accc9b9afe872ce91e791df2dde0";
    src = fetchFromGitHub ({
      owner = "simrat39";
      repo = "rust-tools.nvim";
      rev = "b297167d9e01accc9b9afe872ce91e791df2dde0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-0R8At6IvWKa7w8XajbRu6VOd19Jd/dJhgyvqTQQXeqM=";
    });
    date = "2023-01-25";
  };
  plugin-telescope-nvim = {
    pname = "plugin-telescope-nvim";
    version = "dce1156ca103b8222e4abbfc63f9c6887abf5ec6";
    src = fetchFromGitHub ({
      owner = "nvim-telescope";
      repo = "telescope.nvim";
      rev = "dce1156ca103b8222e4abbfc63f9c6887abf5ec6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-Gq3MFAYd65sNJU7Lb926ZPYqdUWsyLQAPZ04Zxoc/1U=";
    });
    date = "2023-01-22";
  };
  plugin-tokyonight-nvim = {
    pname = "plugin-tokyonight-nvim";
    version = "affb21a81e6d7de073378eb86d02864c594104d9";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "tokyonight.nvim";
      rev = "affb21a81e6d7de073378eb86d02864c594104d9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-ZRNh8YzkJoqWNokmLP5WEqPyT+5I814ojrW7WgXWr+s=";
    });
    date = "2023-01-23";
  };
  plugin-vim-be-good = {
    pname = "plugin-vim-be-good";
    version = "c290810728a4f75e334b07dc0f3a4cdea908d351";
    src = fetchFromGitHub ({
      owner = "ThePrimeagen";
      repo = "vim-be-good";
      rev = "c290810728a4f75e334b07dc0f3a4cdea908d351";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-eWKJrKb80YxNPCLuWdMAuiUrVy6R3Dua1hRw8SzCTfQ=";
    });
    date = "2022-11-08";
  };
  tree-sitter-beancount = {
    pname = "tree-sitter-beancount";
    version = "d52c7e33be77e49ccf976d82216f67b7d4436769";
    src = fetchFromGitHub ({
      owner = "polarmutex";
      repo = "tree-sitter-beancount";
      rev = "d52c7e33be77e49ccf976d82216f67b7d4436769";
      fetchSubmodules = false;
      sha256 = "sha256-ZDa9WTiJ9uTdcF1CmJ4UWOqspG3UtcH0KHPnzHRCXAk=";
    });
    date = "2023-01-27";
  };
}
