# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-dap = {
    pname = "nvim-dap";
    version = "0.6.0";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap";
      rev = "0.6.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-1tFgtvuMxjdlTuq/pzOx6ldGm3/6Hz6aXo6GrSmFFlo=";
    };
  };
}
