# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  sqlite-lua = {
    pname = "sqlite-lua";
    version = "v1.2.2";
    src = fetchFromGitHub {
      owner = "kkharji";
      repo = "sqlite.lua";
      rev = "v1.2.2";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-lBvHU3zKYmU99DhGhBRnOuLWOlG4LyXt+TtrpLsCOh8=";
    };
  };
}
