# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lazy-nvim = {
    pname = "lazy-nvim";
    version = "v10.5.1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "v10.5.1";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-UvDm8OAGOPXfssvuT6OhWnMMTN5D0RkRs45Xt4YXDPI=";
    };
  };
}
