# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lazy-nvim = {
    pname = "lazy-nvim";
    version = "v10.7.1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "v10.7.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-+NZ21sUbjvtG6P41e9QZCfRR5RwZl/C05V/5/IZZnJg=";
    };
  };
}
