# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lazy-nvim = {
    pname = "lazy-nvim";
    version = "v10.13.1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "lazy.nvim";
      rev = "v10.13.1";
      fetchSubmodules = false;
      sha256 = "sha256-3S76f64l+Iot87Kwg6GwPbWO0IjcUy37RLrW4lJ/AQk=";
    };
  };
}
