# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "a8fa6a36f09f00d32577fae0b3cee2f25ffc5c74";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "SchemaStore.nvim";
      rev = "a8fa6a36f09f00d32577fae0b3cee2f25ffc5c74";
      fetchSubmodules = false;
      sha256 = "sha256-Xq+Ar+hMhiQQuTHsl/hHMeNnvGIMfVPd7cl8p3Qolv0=";
    };
    date = "2023-10-18";
  };
}
