# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "3de0cf898d0d771533ea7fb02a09a448bc10b1e5";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "SchemaStore.nvim";
      rev = "3de0cf898d0d771533ea7fb02a09a448bc10b1e5";
      fetchSubmodules = false;
      sha256 = "sha256-lLLimrU6FxEfPHfAL3m6HmzJDqAnsD4lz6N6ZydGZvU=";
    };
    date = "2024-01-25";
  };
}
