# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  schemastore-nvim = {
    pname = "schemastore-nvim";
    version = "6316dc88db89d97d190f24547adddd13569fb746";
    src = fetchFromGitHub {
      owner = "b0o";
      repo = "SchemaStore.nvim";
      rev = "6316dc88db89d97d190f24547adddd13569fb746";
      fetchSubmodules = false;
      sha256 = "sha256-DfKulwXj58jp5aPoMtCcbmvqKYEbe4cQnu8Ui2eEhmI=";
    };
    date = "2023-11-21";
  };
}
