# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "v3.7.10";
    src = fetchFromGitHub {
      owner = "epwalsh";
      repo = "obsidian.nvim";
      rev = "v3.7.10";
      fetchSubmodules = false;
      sha256 = "sha256-sM+0tRRY8nhYWNHs2qJP18URwYEyBK7RKbjTHfMOWfo=";
    };
  };
}
