# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yanky-nvim = {
    pname = "yanky-nvim";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "gbprod";
      repo = "yanky.nvim";
      rev = "v1.0.1";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-IkOO/iUdbKMFYkK8sxPjOww6BwHU7I/o+c1nPK/c8xk=";
    };
  };
}
