# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  yanky-nvim = {
    pname = "yanky-nvim";
    version = "v1.0.1";
    src = fetchFromGitHub {
      owner = "gbprod";
      repo = "yanky.nvim";
      rev = "v1.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-ZRU01wItbsbMFMCU7kTxEdLuk42WvOOqkkL/vXuDTho=";
    };
  };
}
