# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  noice-nvim = {
    pname = "noice-nvim";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "noice.nvim";
      rev = "v2.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-7lgJK5pkMqwIXNeBDsz4B8UAKnkpUvDrHdeG/aSFRzM=";
    };
  };
}
