# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  noice-nvim = {
    pname = "noice-nvim";
    version = "v1.16.1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "noice.nvim";
      rev = "v1.16.1";
      fetchSubmodules = false;
      sha256 = "sha256-TBiUpYgYXskSkq/Camxttxop300H0s22j5yfkvvpDDY=";
    };
  };
}
