# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  trouble-nvim = {
    pname = "trouble-nvim";
    version = "v2.8.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "v2.8.0";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-a+Hi+fbo/JEX/CjZRsvC3RCYuApz6PeBzZmSG0Gznp8=";
    };
  };
}
