# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  trouble-nvim = {
    pname = "trouble-nvim";
    version = "v2.10.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "trouble.nvim";
      rev = "v2.10.0";
      fetchSubmodules = false;
      sha256 = "sha256-8nLghiueYOtWY7OGVxow9A2G/5lgt+Kt5D8q1xeJvVg=";
    };
  };
}
