# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dressing-nvim = {
    pname = "dressing-nvim";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "v2.0.1";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-TukBtfUjjiGHMnl0GSt7D+gbIP0GAJAQXyxHltiYf/M=";
    };
  };
}
