# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dressing-nvim = {
    pname = "dressing-nvim";
    version = "v2.0.1";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "dressing.nvim";
      rev = "v2.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-d2nID4ggbwfw8kVEcV7RGwtq04xos9sLOaVN0tA+6VY=";
    };
  };
}
