# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-navic = {
    pname = "nvim-navic";
    version = "0ffa7ffe6588f3417e680439872f5049e38a24db";
    src = fetchFromGitHub {
      owner = "SmiteshP";
      repo = "nvim-navic";
      rev = "0ffa7ffe6588f3417e680439872f5049e38a24db";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-ndNHJDu7XaEp9RzrwYkbRgSWgoNXwOjAtjVu2lhmAc4=";
    };
    date = "2023-09-18";
  };
}
