# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  vim-be-good = {
    pname = "vim-be-good";
    version = "c290810728a4f75e334b07dc0f3a4cdea908d351";
    src = fetchFromGitHub {
      owner = "ThePrimeagen";
      repo = "vim-be-good";
      rev = "c290810728a4f75e334b07dc0f3a4cdea908d351";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-sFqUksXPjejd9rc2+3VPwFgr0bzYjIzlFLO9ziCBBag=";
    };
    date = "2022-11-08";
  };
}
