# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-dap-virtual-text = {
    pname = "nvim-dap-virtual-text";
    version = "baa5b0dc6663284cce32e0d00ac1f2511b13496f";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "baa5b0dc6663284cce32e0d00ac1f2511b13496f";
      fetchSubmodules = false;
      sha256 = "sha256-1VEEdes7sOagVeX5zjz7R+kNAbfd5NV+sX5xeBGq2Iw=";
    };
    date = "2024-03-10";
  };
}
