# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-dap-virtual-text = {
    pname = "nvim-dap-virtual-text";
    version = "d4542ac257d3c7ee4131350db6179ae6340ce40b";
    src = fetchFromGitHub {
      owner = "theHamsta";
      repo = "nvim-dap-virtual-text";
      rev = "d4542ac257d3c7ee4131350db6179ae6340ce40b";
      fetchSubmodules = false;
      sha256 = "sha256-IJMdDcrfsNfxd4rvLVCD1L2FL7Tzm6dV8c0mtEo98vU=";
    };
    date = "2023-12-28";
  };
}
