# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  overseer-nvim = {
    pname = "overseer-nvim";
    version = "v1.2.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "overseer.nvim";
      rev = "v1.2.0";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-EneT0l5FaruJElLTqH+cEKhKSNj+dvyvknhn+bsJr1U=";
    };
  };
}
