# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  overseer-nvim = {
    pname = "overseer-nvim";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "overseer.nvim";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-CIMzdwGUZ5+/NFm+NoF2BypHVYG++KVrBXqxmETKXQ4=";
    };
  };
}
