# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "23ba63028c6acca29be6462c0a291fc4a1b9eae8";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "23ba63028c6acca29be6462c0a291fc4a1b9eae8";
      fetchSubmodules = false;
      sha256 = "sha256-rtwm8pVsagN4/Cunlt74+BGBx+33xSRi5MwrDFlFepM=";
    };
    date = "2024-03-28";
  };
}
