# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "59d4c14a1a4262cf637ff2420032593afa062749";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "59d4c14a1a4262cf637ff2420032593afa062749";
      fetchSubmodules = false;
      sha256 = "sha256-+eOG+HGqxTFstRIxmJGdcHVnpIxad3lwmjMRldAYGAs=";
    };
    date = "2024-01-15";
  };
}
