# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}: {
  nvim-treesitter = {
    pname = "nvim-treesitter";
    version = "19c6b0c4c9b35962e45b782e2b85a3214d2ac4d5";
    src = fetchFromGitHub {
      owner = "nvim-treesitter";
      repo = "nvim-treesitter";
      rev = "19c6b0c4c9b35962e45b782e2b85a3214d2ac4d5";
      fetchSubmodules = false;
      sha256 = "sha256-1K+vg99QjM7UiMLMN7m4trZYFR33BwyHZlsPOe6UOqE=";
    };
    date = "2024-04-25";
  };
}
