# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nui-nvim = {
    pname = "nui-nvim";
    version = "0.2.0";
    src = fetchFromGitHub {
      owner = "MunifTanjim";
      repo = "nui.nvim";
      rev = "0.2.0";
      fetchSubmodules = false;
      deepClone = true;
      leaveDotGit = true;
      sha256 = "sha256-DnU8Esan4znC9eCK5s9xZsHyd9SZFSq1ic9JHQ7Q0i8=";
    };
  };
}
