# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cmp-emoji = {
    pname = "cmp-emoji";
    version = "19075c36d5820253d32e2478b6aaf3734aeaafa0";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-emoji";
      rev = "19075c36d5820253d32e2478b6aaf3734aeaafa0";
      fetchSubmodules = false;
      sha256 = "sha256-zc5GNkwdVHaeEoCer9tz40F2Xc8qTzPw6NbgkMjjWQI=";
    };
    date = "2021-09-28";
  };
}
