# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cmp-emoji = {
    pname = "cmp-emoji";
    version = "e8398e2adf512a03bb4e1728ca017ffeac670a9f";
    src = fetchFromGitHub {
      owner = "hrsh7th";
      repo = "cmp-emoji";
      rev = "e8398e2adf512a03bb4e1728ca017ffeac670a9f";
      fetchSubmodules = false;
      sha256 = "sha256-Sdgetlwhhc11ufDJH6uaXtbL0EZQFZ2Qgg5yBfG1u7I=";
    };
    date = "2024-03-20";
  };
}
