# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-dap-python = {
    pname = "nvim-dap-python";
    version = "e0be843877e7ae756ef1ee7a441ca0b9e1677da9";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "e0be843877e7ae756ef1ee7a441ca0b9e1677da9";
      fetchSubmodules = false;
      sha256 = "sha256-dNkSpHyiQERy7bLNa0sJgah/oWr9tHxANsnZ7FUXK3Y=";
    };
    date = "2023-11-15";
  };
}
