# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-dap-python = {
    pname = "nvim-dap-python";
    version = "66560f0ebddf96604f7037e1efad3ba6942761e6";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "66560f0ebddf96604f7037e1efad3ba6942761e6";
      fetchSubmodules = false;
      sha256 = "sha256-c3glIPw0gjRTmMmnyY12iAT1Xfl50GlFjRH4OEo2iXk=";
    };
    date = "2024-02-19";
  };
}
