# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-dap-python = {
    pname = "nvim-dap-python";
    version = "3dffa58541d1f52c121fe58ced046268c838d802";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-dap-python";
      rev = "3dffa58541d1f52c121fe58ced046268c838d802";
      fetchSubmodules = false;
      sha256 = "sha256-VK4II8Q1uyd+tVR82Y4myiH0e/ZSWeF5yhweuDnaTE4=";
    };
    date = "2024-04-10";
  };
}
