# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  friendly-snippets = {
    pname = "friendly-snippets";
    version = "d5f74ce4dfdd82848f3f4eac65fe6e29ac5df4c2";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "d5f74ce4dfdd82848f3f4eac65fe6e29ac5df4c2";
      fetchSubmodules = false;
      sha256 = "sha256-KvWH94QV8cgGzNsoYyLFnf6oSXC6Jqk401PINr45Qhg=";
    };
    date = "2024-04-28";
  };
}
