# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  friendly-snippets = {
    pname = "friendly-snippets";
    version = "dcd4a586439a1c81357d5b9d26319ae218cc9479";
    src = fetchFromGitHub {
      owner = "rafamadriz";
      repo = "friendly-snippets";
      rev = "dcd4a586439a1c81357d5b9d26319ae218cc9479";
      fetchSubmodules = false;
      sha256 = "sha256-EY/XCZFuVdHdF0lrQuHm4h7gkv/JyzXldxc+OFAzYoA=";
    };
    date = "2024-02-24";
  };
}
