# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  luasnip = {
    pname = "luasnip";
    version = "v2.0.0";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "v2.0.0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-4+zNNCG6acb8HOXI3PkH45+vdO9HQg2JPhBXIlRcgJo=";
    };
  };
}
