# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-lint = {
    pname = "nvim-lint";
    version = "32f98300881f38f4e022391f240188fec42f74db";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "32f98300881f38f4e022391f240188fec42f74db";
      fetchSubmodules = false;
      sha256 = "sha256-iDBMsQTkveEQtpM19rz9QO3O0dw8sjstBwfh3/soAnc=";
    };
    date = "2023-12-17";
  };
}
