# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-lint = {
    pname = "nvim-lint";
    version = "889dc0ab3f458997eb9d831dbc3b6c4d6fbc2e12";
    src = fetchFromGitHub {
      owner = "mfussenegger";
      repo = "nvim-lint";
      rev = "889dc0ab3f458997eb9d831dbc3b6c4d6fbc2e12";
      fetchSubmodules = false;
      sha256 = "sha256-TF6spbLn0soo2SUzotgbXNDXHbLUg3Z3KI8H3tdK1Kc=";
    };
    date = "2024-02-14";
  };
}
