# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "a851380fbea4c1312d11f13d5cdc86a7a19808dd";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "a851380fbea4c1312d11f13d5cdc86a7a19808dd";
      fetchSubmodules = false;
      sha256 = "sha256-Y7BL2uIeqFXC/Z69vuEFd0MWwxJr5uthJXpDqElB2So=";
    };
    date = "2024-03-15";
  };
}
