# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "794bba734ec95eaff9bb82fbd112473be2087283";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "794bba734ec95eaff9bb82fbd112473be2087283";
      fetchSubmodules = false;
      sha256 = "sha256-gc+8GgFSM87dbcYUW8d9If3qY80xJMmy48vnVezNLPk=";
    };
    date = "2024-04-29";
  };
}
