# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-web-devicons = {
    pname = "nvim-web-devicons";
    version = "cdbcca210cf3655aa9b31ebf2422763ecd85ee5c";
    src = fetchFromGitHub {
      owner = "nvim-tree";
      repo = "nvim-web-devicons";
      rev = "cdbcca210cf3655aa9b31ebf2422763ecd85ee5c";
      fetchSubmodules = false;
      sha256 = "sha256-Cdm607PAFuJ5hfgnVO9wT3UP19h+Cnzkl4yV8r5YfaE=";
    };
    date = "2023-11-20";
  };
}
