# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  conform-nvim = {
    pname = "conform-nvim";
    version = "v5.2.1";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "conform.nvim";
      rev = "v5.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-n5Aes/ckpi5tJyIaDORUaFvZ45DF110PAb5BVeqKkOQ=";
    };
  };
}
