# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gitsigns-nvim = {
    pname = "gitsigns-nvim";
    version = "fa052c20aa7cc62ce6a328c7f3bd556c93b5370e";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "fa052c20aa7cc62ce6a328c7f3bd556c93b5370e";
      fetchSubmodules = false;
      sha256 = "sha256-AJZt7+tVJJSGUn5OAnJcDi9RXFd1UyRRlXIvBPU8KkI=";
    };
    date = "2024-04-04";
  };
}
