# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gitsigns-nvim = {
    pname = "gitsigns-nvim";
    version = "0a2a93f687ec051292943a4d139366332ac93688";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "0a2a93f687ec051292943a4d139366332ac93688";
      fetchSubmodules = false;
      sha256 = "sha256-G24BAwQR8iENLddXcDXmmME8g+djw6vb28DY8Gh8akY=";
    };
    date = "2024-01-25";
  };
}
