# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  gitsigns-nvim = {
    pname = "gitsigns-nvim";
    version = "ff01d34daaed72f271a8ffa088a7e839a60c640f";
    src = fetchFromGitHub {
      owner = "lewis6991";
      repo = "gitsigns.nvim";
      rev = "ff01d34daaed72f271a8ffa088a7e839a60c640f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-yQ1nJRpL/yB9dka2cWIo4pLcUmVm4gSt2FPwZHBCp3o=";
    };
    date = "2023-10-06";
  };
}
