# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "d0467b9574b48429debf83f8248d8cee79562586";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "d0467b9574b48429debf83f8248d8cee79562586";
      fetchSubmodules = false;
      sha256 = "sha256-8io/dDbFRUyBgzg+oVdpJCGhm59d+AwstyHs9OAWlkY=";
    };
    date = "2023-10-29";
  };
}
