# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-lspconfig = {
    pname = "nvim-lspconfig";
    version = "29939f6f07bc0f3b9fc563fbfbee06ac88c8c439";
    src = fetchFromGitHub {
      owner = "neovim";
      repo = "nvim-lspconfig";
      rev = "29939f6f07bc0f3b9fc563fbfbee06ac88c8c439";
      fetchSubmodules = false;
      sha256 = "sha256-mT9T3k10REUpk/R2rQNPtG25XkRjgNJfe+ygqBfpePY=";
    };
    date = "2023-11-17";
  };
}
