# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neogit = {
    pname = "neogit";
    version = "93bf00cd5db1e88ea0ca9105e83f7e97896a7cd2";
    src = fetchFromGitHub {
      owner = "NeogitOrg";
      repo = "neogit";
      rev = "93bf00cd5db1e88ea0ca9105e83f7e97896a7cd2";
      fetchSubmodules = false;
      sha256 = "sha256-GXtSgk7fzHmagc3ZyRvhPCXcHfiSANhYK5uX0PJG8OU=";
    };
    date = "2024-01-04";
  };
}
