# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neogit = {
    pname = "neogit";
    version = "3718664bb62e89930f0c3c836188c2a4f44fa119";
    src = fetchFromGitHub {
      owner = "NeogitOrg";
      repo = "neogit";
      rev = "3718664bb62e89930f0c3c836188c2a4f44fa119";
      fetchSubmodules = false;
      sha256 = "sha256-iv9hILUEtzJVo1MIc1HtRd56p5nrFmTmW/NaJrSyLSY=";
    };
    date = "2023-12-28";
  };
}
