# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  neogit = {
    pname = "neogit";
    version = "acd391ebb607cd6b8dd1c3e95c8fe8ebccfaf4fb";
    src = fetchFromGitHub {
      owner = "NeogitOrg";
      repo = "neogit";
      rev = "acd391ebb607cd6b8dd1c3e95c8fe8ebccfaf4fb";
      fetchSubmodules = false;
      sha256 = "sha256-yWocGsJo6Vpxxzy5zLa0weSWqsEQd4NFDQPXw3xCAQk=";
    };
    date = "2024-01-14";
  };
}
