# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  nvim-dap-ui = {
    pname = "nvim-dap-ui";
    version = "v3.9.1";
    src = fetchFromGitHub {
      owner = "rcarriga";
      repo = "nvim-dap-ui";
      rev = "v3.9.1";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-k06UhT31j4peEv9dKLlVIKbXLBFHQSWIIQY/74Pti6U=";
    };
  };
}
