# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  mini-indentscope = {
    pname = "mini-indentscope";
    version = "v0.11.0";
    src = fetchFromGitHub {
      owner = "echasnovski";
      repo = "mini.indentscope";
      rev = "v0.11.0";
      fetchSubmodules = false;
      sha256 = "sha256-TAHFx0QTL/rTKG+Y6+4zJVUWv5Dau/WAN4t8Wgsn10U=";
    };
  };
}
