# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  kanagawa-nvim = {
    pname = "kanagawa-nvim";
    version = "ab41956c4559c3eb21e713fcdf54cda1cb6d5f40";
    src = fetchFromGitHub {
      owner = "rebelot";
      repo = "kanagawa.nvim";
      rev = "ab41956c4559c3eb21e713fcdf54cda1cb6d5f40";
      fetchSubmodules = false;
      sha256 = "sha256-R/rEV7SU/eZfs+aQQR2D2Z+zRHNI4DsCSflCdN0kMT4=";
    };
    date = "2024-02-12";
  };
}
