# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  beancount-nvim = {
    pname = "beancount-nvim";
    version = "52dcd779a7a15d0ff1f05054cf5a82ba6616d781";
    src = fetchFromGitHub {
      owner = "polarmutex";
      repo = "beancount.nvim";
      rev = "52dcd779a7a15d0ff1f05054cf5a82ba6616d781";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-D9FbcaIMLPoumlfxtz3mTWLZLtxgLgLHPzDEl4DMMaE=";
    };
    date = "2023-09-02";
  };
}
