# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  which-key-nvim = {
    pname = "which-key-nvim";
    version = "v1.6.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "which-key.nvim";
      rev = "v1.6.0";
      fetchSubmodules = false;
      sha256 = "sha256-EVGIe8wUoKdND40vuyqT6+EOY6aUFBpY8PXivvL3ZZM=";
    };
  };
}
