# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  git-worktree-nvim = {
    pname = "git-worktree-nvim";
    version = "ee1030d6b987f381c05f7228565a63e124e93ad3";
    src = fetchFromGitHub {
      owner = "polarmutex";
      repo = "git-worktree.nvim";
      rev = "ee1030d6b987f381c05f7228565a63e124e93ad3";
      fetchSubmodules = false;
      sha256 = "sha256-2XgPF8uzLgyDUGBiqZJZN/jWV369jqfkPGEHnyeG6KI=";
    };
    date = "2024-01-04";
  };
}
