# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  git-worktree-nvim = {
    pname = "git-worktree-nvim";
    version = "36091e6be0391c5a8a46c0f3a0ea4ad90885aed3";
    src = fetchFromGitHub {
      owner = "polarmutex";
      repo = "git-worktree.nvim";
      rev = "36091e6be0391c5a8a46c0f3a0ea4ad90885aed3";
      fetchSubmodules = false;
      sha256 = "sha256-OaEKvScOu4Y8c2T4h+I6noI27dEWG9uETXOhPQ6jvzI=";
    };
    date = "2024-01-22";
  };
}
