# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  edgy-nvim = {
    pname = "edgy-nvim";
    version = "v1.8.2";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "edgy.nvim";
      rev = "v1.8.2";
      fetchSubmodules = false;
      sha256 = "sha256-4lE+Uo1uxrqxEzx4lDyH35FNQbE95htSV2IDuJJkgLs=";
    };
  };
}
