# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  edgy-nvim = {
    pname = "edgy-nvim";
    version = "v1.8.1";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "edgy.nvim";
      rev = "v1.8.1";
      fetchSubmodules = false;
      sha256 = "sha256-qjpNNcWUx9nVv4P6iaSRZsG7GxheEkjk3OJHjscVlX0=";
    };
  };
}
