# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  edgy-nvim = {
    pname = "edgy-nvim";
    version = "v1.8.3";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "edgy.nvim";
      rev = "v1.8.3";
      fetchSubmodules = false;
      sha256 = "sha256-mx7E7ov09IN1UueAEsQ5OFNs05h4hw+v4y7ot+0JuxE=";
    };
  };
}
