# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  tokyonight-nvim = {
    pname = "tokyonight-nvim";
    version = "v2.9.0";
    src = fetchFromGitHub {
      owner = "folke";
      repo = "tokyonight.nvim";
      rev = "v2.9.0";
      fetchSubmodules = false;
      sha256 = "sha256-NOKzXsY+DLNrykyy2Fr1eiSpYDiBIBNHL/7PPvbgbSo=";
    };
  };
}
